### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Ymaril** [trmid/world-hash#1]
I find this project as socially important as possible. I am learning about the implementation of cryptocurrencies just to be ready to help the world with the implementation of a zero trust decentralized minecraft world.
I have some thoughts on a possible project architecture.
I want to talk about the project and, probably, participate in the development. I am available in social networks under the same nickname.

**Comment by trmid** [comment]
Hi @Ymaril, thanks for your interest.

Just as a clarification, this project is not centered around cryptocurrencies or cryptocurrency transactions, but will be using crypto-adjacent technologies like IPFS and ENS. We are developing WorldHash as a part of the ETHOnline hackathon this month and will have a prototype shortly. If you'd like to contribute any ideas or feedback I'd be happy to receive it.

Cheers!
